Munkleson/game-swap

Gemfile, Gemfile.lock, app/models/user.rb, app/views/layouts/application.html.erb, config/environments/development.rb, config/environments/production.rb, config/initializers/devise.rb, config/locales/devise.en.yml, config/routes.rb, db/migrate/20250118080137_devise_create_users.rb, db/schema.rb, test/models/user_test.rb
Added the User model via Devise. Model also has first and last name, and username
=> Devise setup

Gemfile.lock
=> Updated ruby version

app/models/listing.rb, app/models/offer.rb, app/models/user.rb, db/migrate/20250118233351_create_offers.rb, db/schema.rb, test/models/offer_test.rb
Added Offer Model, and relationships. Need to discuss validations for model. Need to add "status" column later (It will be an enum).  
Also added relationship between User and Listing models.
=> Add Offer Model and offers table, add relationship for User and Listing

app/controllers/dashboard_controller.rb, app/controllers/listings_controller.rb, app/controllers/offers_controller.rb, test/controllers/dashboard_controller_test.rb, test/controllers/listings_controller_test.rb, test/controllers/offers_controller_test.rb
Added controllers for Listings, Offers, and Dashboard. All actions are empty.
=> Set up controllers

app/controllers/listings_controller.rb, app/controllers/offers_controller.rb
I added the empty views, including the forms. I also realized I added an index action to the offers controller that we did not need, so I removed it.
=> Added views, updated controllers

app/models/listing.rb, app/models/offer.rb, db/migrate/20250121111147_edit_listings_table.rb, db/schema.rb
Edited the listing model. Removed image_url, game_info, and title, as… this data will be from the Games table etc. Added some validations for the models
=> Listing model edit and validations for all models

app/controllers/dashboard_controller.rb, app/javascript/application.js, app/javascript/dashboard/dashboard_tabs.js, app/views/dashboard/_dashboard_listings.html.erb, app/views/dashboard/_dashboard_offers.html.erb, app/views/dashboard/index.html.erb, config/routes.rb
Added a dashboard page with offers and listings buttons to tab between the two views. Offers and listings also display the respective offers and listings owned by the user with minimal style
=> Dashboard basic functionality

app/controllers/pages_controller.rb, db/migrate/20250121160138_change_games_slug_to_custom_search_name.rb, db/schema.rb, db/seeds.rb, znotes.txt
Removed the slug column from games and changed it to a search name, which is a further simplified version of the name, removing spaces, special characters, and such.
Search name is created when seeding
=> Search functionality database-side

app/assets/stylesheets/pages/_home.scss, app/controllers/pages_controller.rb, app/views/pages/home.html.erb
Fixed the search bar function, however the results of the search function are still in the homepage. We discussed that results should go to another page which is listing (index). Please check!
=> Fix search bar homepage

Gemfile, Gemfile.lock, db/schema.rb, db/seeds.rb
=> seed for offer model completed

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/pages/_home.scss, app/assets/stylesheets/pages/_landing.scss, app/controllers/pages_controller.rb, app/models/game.rb, app/views/layouts/application.html.erb, app/views/pages/home.html.erb, app/views/shared/_footer.html.erb, db/seeds.rb
I just updated the search funtion, instead of using the game.name I change it to game.search. 
However, I'm not quite sure if we just rely it from the seed file or we have to make a real function like this. 
This is the Game model, define the funtion there:
`class Game < ApplicationRecord
has_many :listings
before_save :set_search_name
private
def set_search_name
self.search_name = name.gsub(/[^a-z0-9]/i, '').downcase
end
end`
After defining the function, we'll have to update the pages controller as well. 
`class PagesController < ApplicationController
skip_before_action :authenticate_user!, only: :home
def home
@query = params.dig(:search, :query)
if @query.present?
normalized_query = @query.gsub(/[^a-z0-9]/i, '').downcase
@listings = Listing.joins(:game).where('games.search_name LIKE …
=> update search function using search_name instead of just name

app/assets/stylesheets/application.scss, app/assets/stylesheets/dashboard/_dashboard.scss, app/controllers/dashboard_controller.rb, app/controllers/listings_controller.rb, app/javascript/controllers/create_listing_controller.js, app/views/dashboard/_create_listing.html.erb, app/views/dashboard/_dashboard_listings.html.erb, config/routes.rb
Created the method and views for creating a listing in the dashboard listings section
=> Dashboard create listings functionality

app/models/game.rb
=> fix game model

app/controllers/games_controller.rb, app/javascript/controllers/create_listing_controller.js, app/views/dashboard/_create_listing.html.erb, config/routes.rb, test/controllers/games_controller_test.rb
Please check and made game controller
=> made the search for game name

app/views/dashboard/_dashboard_listings.html.erb
=> Add Link to offers from listing

app/controllers/games_controller.rb, app/javascript/controllers/create_listing_controller.js, app/views/listings/_create_offer.erb, app/views/pages/home.html.erb
Made search function on homepage have a dropdown too. Refactored the create offer form to work correctly
=> Game search functionality on home page

app/views/pages/home.html.erb
Changed the col-# for some elements
=> Fixed visuals for search results not being the correct size

Gemfile, Gemfile.lock, config/initializers/geocoder.rb, db/migrate/20250128012407_add_coordinates_to_user.rb, db/migrate/20250128051444_add_genres_to_games.rb, db/schema.rb, db/seeds.rb
Also added it in the seeding part for games
=> Added the genres column in games that was forgotten in the previous PR

Gemfile, Gemfile.lock, app/controllers/listings_controller.rb, app/models/listing.rb, app/views/dashboard/_create_listing.html.erb, app/views/listings/show.html.erb, config/environments/development.rb, config/environments/production.rb, config/storage.yml, db/migrate/20250127150114_create_active_storage_tables.active_storage.rb, db/schema.rb
Added ability for the user to upload their own photos 
Please ignore the styling it is only there to make sure that the photos were uploaded!
=> User uploaded images

app/controllers/listings_controller.rb, app/javascript/controllers/sort_listings_controller.js, db/schema.rb
Fixed a bug where empty input from the home page would render nothing in the listings, rather than all listings. Also refactored code in the sort listings controller to align with stimulus conventions, as well as binding event listener to document for this instance
=> Fix empty listings bug and refactor sort listings js controller

app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_links.html.erb
Made the sign up and login form look presentable
=> Devise Form

app/assets/stylesheets/application.scss, app/assets/stylesheets/listings/_sort_and_filter.scss, app/controllers/listings_controller.rb, app/javascript/controllers/filter_listings_controller.js, app/javascript/controllers/slider_filters_controller.js, app/views/listings/_filter_menus.html.erb, app/views/listings/index.html.erb, app/views/listings/show.html.erb
More filter functionality. Sliders now work full, show a min and max value, as well as the current value. Also added a duration filter, where you can input your wanted duration range. Filters are saved across searches, but not page reload
=> Filter functionality

app/controllers/listings_controller.rb, app/models/listing.rb, app/views/dashboard/_create_listing.html.erb
Added logic to limit the number of photos a user can upload when creating a listing to 4. 
Added validations in the model and logic in the controller.
=> Add limit to user uploaded photos for listings

app/controllers/chats_controller.rb, app/controllers/offers_controller.rb, app/javascript/controllers/chats_controller.js, app/views/chats/_chats.html.erb, app/views/chats/_redirect_from_offers.html.erb, app/views/chats/index.html.erb, app/views/offers/index.html.erb, config/routes.rb
- Added logic for when an offer is accepted, you can start a chat with the person whose offer you accepted. 
- Going to chats this way will also render the messages of the person (if there are any already) and select the chat
=> New chat after accepting offer

app/assets/stylesheets/chats/_index.scss, app/assets/stylesheets/components/_navbar.scss, app/controllers/application_controller.rb, app/controllers/chats_controller.rb, app/javascript/controllers/chats_controller.js, app/javascript/controllers/dashboard_controller.js, app/views/chats/_chats.html.erb, app/views/chats/_messages.html.erb, app/views/chats/_new_message.html.erb, app/views/chats/_unread_counter.html.erb, app/views/shared/_navbar.html.erb, config/routes.rb, db/migrate/20250130113327_add_read_status_to_messages.rb, db/schema.rb, db/seeds.rb
- Messages now refresh on a regular basis to check for new messages that have been entered by other users
- This is until we can figure out turbo streams and subscribing to a channel
- Unread messages now have a counter if it is more than 0. Total unread messages appears on the nav bar, while each sidebar chat shows how many unread messages there are
- Clicking into a chat clears all unread messages (whether you have actually scrolled up to read them or not)
=> Messages functionality improvement

app/assets/stylesheets/pages/_landing.scss, app/views/pages/home.html.erb
I just fixed the banner responsiveness.
=> fixed the banner responsiveness

app/assets/stylesheets/components/_carousel.scss, app/controllers/pages_controller.rb, app/views/pages/home.html.erb, db/schema.rb, db/seeds.rb
Updated the home page. 
- made additional carousels with the same behaviour of the first carousel. 
- randomized 2 genre every reload of the page and display the games. If there's no games that is being listed to the specific genre, it will just be blank.
=> Homepage carousel category (additional carousel)

app/controllers/chats_controller.rb, app/javascript/controllers/chats_controller.js, app/views/chats/_messages.html.erb, app/views/chats/_redirect_from_offers.html.erb
- Fixed issue of messages not working when coming from the offers page
- Fixed chat and messages not working
=> Fixed chat issues

app/javascript/controllers/chats_controller.js
- Was selecting an element from the wrong parent element
=> Fixed minor issue of chats not refreshing

app/assets/stylesheets/chats/_index.scss, app/controllers/chats_controller.rb, app/javascript/controllers/chats_controller.js, app/views/chats/_messages.html.erb, app/views/chats/_new_message.html.erb, app/views/chats/index.html.erb, config/routes.rb, db/seeds.rb
Fixed further bugs of messages not showing when someone else posts. Messages unread counter also updates when a new message comes in and you are not scrolled to the bottom, and when you do, it updates read in the database for that message too
=> Further fixing of chat functionality

app/assets/stylesheets/chats/_index.scss, app/javascript/controllers/chats_controller.js, db/schema.rb, db/seeds.rb
- More robust seeding method for users, chats, and messages, especially for a demo
- Message seeding content now uses lorem ipsum
=> Enhanced seeding

app/assets/stylesheets/dashboard/_dashboard_offers.scss, app/views/dashboard/_dashboard_offers.html.erb
=>  give a scss class for icon

app/javascript/controllers/dashboard_controller.js, app/views/dashboard/_create_listing.html.erb, app/views/dashboard/_dashboard_listings.html.erb, app/views/dashboard/_dashboard_offers.html.erb, app/views/dashboard/index.html.erb, app/views/users/_user_form.html.erb
Updated the buttons naming convention that is not developer words
=> Fixed buttons naming and create a game form
